//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccounts
    {
        public string BranchNumber { get; set; }
        public string AccountNumber { get; set; }
        public string Identity { get; set; }
        public string BankName { get; set; }
        public string BankNumber { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
