//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loans
    {
        public int Id { get; set; }
        public System.DateTime ReturnLoanGeorgianDate { get; set; }
        public string ReturnLoanHebrewDate { get; set; }
        public string BorrowerIdentity { get; set; }
        public string AccountNumberBorrower { get; set; }
        public string NoteOfReturnLoan { get; set; }
        public string WayOfPay { get; set; }
        public int LoanSum { get; set; }
        public int DebtBalance { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
