//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MilgaPluseDBEntities : DbContext
    {
        public MilgaPluseDBEntities()
            : base("name=MilgaPluseDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BankAccounts> BankAccounts { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Loans> Loans { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Scholarships> Scholarships { get; set; }
    }
}
