//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scholarships
    {
        public int Id { get; set; }
        public string Identity { get; set; }
        public string HebrewMonth { get; set; }
        public string HebrewYear { get; set; }
        public System.DateTime Date { get; set; }
        public int Basic { get; set; }
        public bool Musar { get; set; }
        public Nullable<int> SumForMusar { get; set; }
        public int Absence { get; set; }
        public string NoteAbsence { get; set; }
        public int SumForAbsence { get; set; }
        public int ShmiratSdarim { get; set; }
        public int SumForShmiratSdarim { get; set; }
        public Nullable<int> addToShmiratSdarimBecauseGoodTest { get; set; }
        public int Atmada { get; set; }
        public string NoteAtmada { get; set; }
        public int SumForAtmada { get; set; }
        public Nullable<int> Mark { get; set; }
        public Nullable<int> SumForMark { get; set; }
        public Nullable<int> ExcellenceScholarship { get; set; }
        public Nullable<int> HolidayScholarship { get; set; }
        public string NoteHolidayScholarship { get; set; }
        public int ReligiousMinistry { get; set; }
        public int Scholarship { get; set; }
        public int ScholarshipsAndLoan { get; set; }
        public int Refund { get; set; }
        public Nullable<int> Donation { get; set; }
        public int RemainderDebt { get; set; }
        public bool Confirm { get; set; }
        public Nullable<int> RefundTransportation { get; set; }
        public string NoteGeneral { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
